### PR TITLE
new spec project to show an example for configurations via DB

### PR DESCRIPTION
**Pull request by yellowbrickc**
Hi Max,

as I promised here my example to configure features via some repository.

### CODE REVIEW

**Comment by mexx** [comment]
Thank you!

**Comment by yellowbrickc** [comment]
I thank you!
Can you please double check the build.fsx? I had some problems with the mspec runner on my machine :(

**Comment by mexx** [comment]
Sure, I'll take a look.

**Comment by mexx** [comment]
Since version 0.9.0 MSpec have its runner in a separate NuGet package.
I've migrated to Paket and added the runner package 543dc4ae6cb345b568ac77194d5434f1a065baf3, now it works as expected.

**Pull request merged**
